version: "3"
services:
#  Create a service named db.
  db:
#   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres:9.6-alpine"
#   Give the container the name my_postgres. You can changes to something else.
    container_name: "main_db"
#   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=mydb
#   Maps port 54320 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5432:5432"
  runner:
    depends_on:
      - db
    stdin_open: true
    tty: true
    image: "jbergknoff/postgresql-client"
    environment:
      - PGPASSWORD=pwd0123456789
    entrypoint:
      - psql
      - postgresql://john:pwd0123456789@db:5432/mydb
    volumes:
      - ./db:/db
    working_dir: /db
  proxy:
    depends_on:
      - server
    image: "envoyproxy/envoy:latest"
    volumes:
      - ./envoy.yml:/etc/envoy/envoy.yaml
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l trace --log-path /tmp/envoy_info.log
    ports:
      - 8080:8080
      - 9901:9901
  server:
    depends_on:
      - db
    image: golang:alpine
    volumes:
      - ./:/app
      - ~/go:/go
    command: go run /app/server.go
    ports:
      - 7777:7777
    environment:
      - DB_USER=john
      - DB_PWD=pwd0123456789
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydb
