---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory
    version: v0
  name: inventory
  namespace: prod
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    # Use named container port.
    targetPort: backend-http
  selector:
    app: inventory
    version: v0